app/Header.tsx

forgot to revert an unneeded change that now uses undefined variables, my bad :/

chore: revert header change using non-existent variables

---

backend/chain.go

feat(backend): update default user image

---

backend/create_event.go
backend/participate.go

fix: ignore email error & avoid rollback db after chain success

---

app/i18n/messages/en.json
components/navigation/header.tsx

feat(front): add create event button in navbar

---

app/event/[id]/participants-section.tsx

fix(front): break line when 2 participants

---

components/form/EventForm.tsx

feat(front): prevent tab focus on tab buttons & directly to description

---

app/i18n/messages/en.json
app/profile/[id]/page.tsx
app/profile/[id]/profile-info.tsx
app/settings/EditUser.tsx
components/form/components/FormFieldInputString.tsx
components/form/components/FormFieldTextArea.tsx
components/navigation/header.tsx

- Usage of new dropdown menu to navigate between `Profile` & `Settings`
- Remove profile & signout buttons from `EditUser`

feat: Improve user profile navigation journey

---

app/event/[id]/ParticipateForm.tsx
app/globals.css
app/i18n/messages/en.json
app/layout.tsx
app/settings/EditUser.tsx
components/cards/Card.tsx
components/common/map/Map.tsx
components/form/EventForm.tsx
components/form/components/FormFieldInputNumber.tsx
components/form/components/FormFieldInputString.tsx
components/form/components/FormFieldLocation.tsx
components/form/components/FormFieldTextArea.tsx
components/form/components/form-field-date-picker.tsx
components/form/components/form-field-image.tsx
components/form/event-form.tsx
components/layout/EventsListLayout.tsx
components/shadcn/button.tsx
components/shadcn/form.tsx
components/shadcn/input.tsx
components/shadcn/label.tsx
components/shadcn/select.tsx
components/shadcn/tabs.tsx
components/shadcn/textarea.tsx
tailwind.config.ts

Fix #302 
Fix #314 
Related #300 
- Clean code `FormFieldDatePicker`

feat(front): cosmetic overhaul

---

components/navigation/header.tsx

fix(front): cursor pointer + hover effect on top avatar

---

backend/chain.go

fix(back): add event isMember func for polls

---

components/cards/social-feed/post-card-layout.tsx

Just sorts Reactions by count descending

fix(feed): Sort Reactions by count

---

components/cards/social-feed/post-card-layout.tsx

Merge to `main` after #246 merged
Fix #402 
**Changes**
Added overflow on reactions list

fix(feed): Reaction overflow

---

app/event/[id]/event-feed.tsx
app/event/[id]/event-info.tsx
components/buttons/go-top-button.tsx

It removes the "sticky bottom" behavior to avoid blinks, UI bugs etc

fix(feed): Remove input sticky

---

components/cards/social-feed/post-card-layout.tsx

chore: adjust emoji render

---

components/cards/social-feed/poll-post-card.tsx

To avoid errors provoked by not participant trying to vote

fix: disable votes when not participant or organizer

---

components/cards/social-feed/post-card-layout.tsx

fix(reactions): Add light theme support, adjust colors

---

lib/web3-img-loader.ts

- pass quality param to ipfs gateway
- request webp format from ipfs gateway

feat: better image optimization params

---

app/event/[id]/page.tsx
components/cards/event-card.tsx
components/common/user.tsx
lib/web3-img-loader.ts

this results in roughly -20% transfer size for image-heavy pages

feat: compress images more

---

backend/create_poll.go
components/form/types.ts
gno/r/polls/polls.gno

fix(back/feed): poll option max 128 char instead of 32

---

app/ticket/[id]/tickets-info.tsx
components/cards/ticket-card.tsx

feat(front): add user email on tickets

---

app/event/[id]/participants-section.tsx
components/common/user.tsx

New: using Drawer for mobile format modal

fix(front): Participation List scroll

---

app/event/[id]/event-info-layout.tsx
app/event/[id]/main-event-sections.tsx
app/i18n/messages/en.json
components/form/event-registration/index.tsx

feat(front): hide participation card until clerk is loaded + clearer error when user is already participant

---

gno/p/basedao/members.gno
gno/p/events/events.gno
gno/p/role_manager/role_manager.gno

fix(chain): optimize count participant

---

.env.backend-dev
backend/mail.go
gno/p/events/events.gno
gno/p/users/users.gno
gno/r/cockpit/render.gno

Fixes #562 
Also need to update vercel env before merge

feat: move pinata gateway under zenao domain

---

backend/gzdb/db.go
backend/gzdb/event.go
backend/ics.go
backend/participate.go
backend/zeni/zeni.go
go.mod
go.sum
migrations/20250619151208_ics-seq-nb.sql
migrations/20250620082945_ics-seq-nb.sql
migrations/atlas.sum
schema.hcl

that's good, when you receive mail with update google client update your calendar without any user interaction
fix #315

feat(back): send ICS file on participation

---

app/event/[id]/scanner/event-ticket-scanner.tsx
components/dialogs/check-in-confirmation-dialog.tsx

After testing on mobile the scanner, I noticed the front camera was selected by default.
I ensured to change that, and allow user to change to select camera in case the default camera selected is not the one the user wants to use

fix(front): Camera selection

---

app/discover/[from]/page.tsx
app/discover/discover-events-list.tsx
app/event/sitemap.ts
app/profile/[address]/page.tsx
app/profile/[address]/profile-info.tsx
app/tickets/[from]/page.tsx
app/tickets/tickets-events-list.tsx
gno/r/eventreg/eventreg.gno
gno/r/eventreg/eventreg_test.gno
gno/r/eventreg/render.gno
lib/queries/events-list.ts

feat(front): infinite scroll while displaying events lists

---

app/i18n/messages/en.json

This PR improves the manifesto by fixing grammar/spelling, and simplifying sentence structure.
- Grammar and fluency fixes (p1–p5, p7)
- Reworded "p6-end" from “to enforce” → “to build” (positive tone)

fix(front): grammar and style improvements in manifesto

---

app/community/[id]/layout.tsx
app/i18n/messages/en.json
components/community/community-join-button.tsx
lib/mutations/community-join.ts

https://github.com/samouraiworld/zenao/issues/645

feat: join community button action

---

app/community/[id]/layout.tsx
app/community/community-info-layout.tsx
components/community/community-edit-button.tsx
components/community/community-join-button.tsx
components/community/community-leave-button.tsx

Fixes https://github.com/samouraiworld/zenao/issues/701

fix(front): move community buttons to the right

---

app/communities/page.tsx
components/community/community-card.tsx
components/user/users-names-preview.tsx

- add gap between community cards
- always show user names line
- improve user names render
- have same avatar rounding in all breakpoints

feat: improve comunities render

---

app/i18n/messages/en.json
app/profile/[address]/profile-header.tsx
app/settings/edit-user.tsx
lib/user-profile-serialization.ts
types/schemas.ts

Related issue: https://github.com/samouraiworld/zenao/issues/709
> where is it better to display the location: under the name and short bio, or below the main bio (like in X)?

feat(front): location to user profile

---

app/settings/edit-user.tsx
components/features/community/community-form.tsx
components/features/event/event-form.tsx
components/widgets/form/form-field-image.tsx

feat: aspect ratio upload hint

---

app/community/[id]/layout.tsx
app/community/community-info-layout.tsx

feat(front): community page metadata + jsonLd
